### ISSUE TITLE
Ready to Reserve Your Dates?

### ISSUE THREAD

**Issue by drrandal** [drrandal/BransonTablerockOasis#1]
I have tried to insert a photo with a hyperlink on the main index page, and failed. Show me how plz. Also, at the bottom where it will link to Facebook, I want a gray version of the VRBO/HomeAway jpg and link - but not sure where you ever inserted those images since they seemed to come from a bootstrap archive.

Point being, I want to "drive" people to the reservations website for our condo:
http://www.vrbo.com/686045

Thanks

**Comment by NathanRSmith** [comment]
Sunday?
