### ISSUE TITLE
Missing images in photogallery.html

### ISSUE THREAD

**Issue by NathanRSmith** [drrandal/BransonTablerockOasis#7]
http://bransontablerockoasis.com/photogallery.html

**Comment by drrandal** [comment]
Okay, so I see there are issues - I am confused as it looks like they are really giving me several options for layout, for one thing. I want the "All" layout I think, that includes each gallery. But, I'm not sure if the others are really galleries or simply one photos. I thought I could label a gallery, have a main photo, and populate it with other related photos, i.e. exterior or main level. Can you determine if this can be done with what is available?

Also, we verbally decided that we didn't need the "detail" portion, as I think even the photo end included the ability to label? If it doesn't include the ability to label photos, then i may need detail.
